sheet = "开发计划统计"
query = """\
select a.jhbb,count(a.jym),count(a.jym)*1.0/(select count(jym)from xmjh where fa not in ("1-下架交易","5-移出柜面系统"))
from kfjh a
left join xmjh b
on a.jym=b.jym
where b.sfwc not like "5%"
group by jhbb
order by jhbb\
"""
name = "开发计划统计"
start_col = "A"

[widths]
"A:C" = 12

[[column]]
name = "计划版本"
total_string = "合计"

[[column]]
name = "交易数量"
format = "Number"
total_function = "sum"

[[column]]
name = "占比"
format = "Percent"
total_function = "sum"
